# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.


variable ASMPath "/opt/programs/vmd/1.9.3/plugins/noarch/portoBioComp/compASM" 


package ifneeded ASM 1.0 [list source [file join $dir ASM.tcl]]
package ifneeded ASM_PATH 1.0 [list source [file join $dir ASM_PATH.tcl]]
package ifneeded ASM_Constant 1.0 [list source [file join $dir ASM_Const.tcl]]
package ifneeded ASM_GUI 1.0 [list source [file join $dir ASM_GUI.tcl]]
package ifneeded pdboperation 1.0 [list source [file join $dir/Core/Routines pdbop.tcl]]
package ifneeded chargefile 1.0 [list source [file join $dir/Core/Routines charge.tcl]]
package ifneeded tleapop 1.0 [list source [file join $dir/Core/Routines tleap.tcl]]
package ifneeded min 1.0 [list source [file join $dir/Core/Routines min_ala.tcl]]
package ifneeded mmpbsa 1.0 [list source [file join $dir/Core/Routines mmpbsa.tcl]]
package ifneeded vmdinfo 1.0 [list source [file join $dir/GUI/Routines vmdinfo.tcl]]
package ifneeded Gui_func 1.0 [list source [file join $dir/GUI/Routines Gui_func.tcl]]
package ifneeded inputframe 1.0 [list source [file join $dir/GUI/Routines inputFrame.tcl]]
package ifneeded outputframe 1.0 [list source [file join $dir/GUI/Routines outputFrame.tcl]]
package ifneeded aboutframe 1.0 [list source [file join $dir/GUI/Routines aboutFrame.tcl]]


package ifneeded math 1.2.4  [list source [file join $dir/Core/LIB/math math.tcl]]
package ifneeded tablelist 4.11 [list source [file join $dir/GUI/LIB/tablelist4.11/ tablelist.tcl]]
package ifneeded Plotchart 1.9.2 [list source [file join $dir/GUI/LIB/plotchart plotchart.tcl]]
